### ISSUE TITLE
Not compatible with VS Code 1.49.1

### ISSUE THREAD

**Issue by theluk** [benawad/vscode-stories#23]
Honestly, I saw the extension on twitter yesterday and then decided to go into office today, ON FREAKING SATURDAY, to try it out as I left my notebook here. But now I must see, that it does not work for my VSCODE. 

![asdf](https://media.giphy.com/media/gd09Y2Ptu7gsiPVUrv/giphy.gif)

![image](https://user-images.githubusercontent.com/580946/97775326-059e4180-1b60-11eb-8d9e-e404b97e3660.png)

**Comment by dephraiim** [comment]
Upgrade to the latest version.

**Comment by TheFern2** [comment]
That's because when you write an extension with yeoman the vscode api is usually the latest version same as vscode version in package.json, and is not backwards compatible.

@benawad can probably decide how much versions he wants to go back to support, because I realize not everyone wants to constantly upgrade and possibly break a working plugin.

Version Compatibility is explained in page below. 

https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by spoon611** [comment]
The extension uses webview to display the stories in the sidebar. This is only available from vscode > 1.50

https://code.visualstudio.com/updates/v1_50#_webview-views

**Comment by TheFern2** [comment]
Yup if using latest features, then yeah extension can't support any old vscode versions kind of a bummer. I know I hate to upgrade vscode everytime due to an extension, but in this case webviews seem like the best choice.

**Comment by theluk** [comment]
thanks guys
